{
 "title": "Spring Boot Demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "systemCpuUsage" }
   ]
  },
  {
   "title": "Used Heap",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 3, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "target": "aggregate(jvmMemoryUsed.area.heap.id.*, 'sum')"
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "graph",
   "gridPos": { "h": 15, "w": 11, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "httpServerRequests.*.*.method.*.outcome.*.status.*.uri._users.mean"
    },
    {
     "target": "httpServerRequests.*.*.method.*.*.*.status.*.uri._users__id_.mean"
    }
   ]
  },
  {
   "title": "Logback",
   "type": "graph",
   "description": "Logback events",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "logbackEvents.level.*.count" }
   ]
  }
 ]
}