server:
  port: 8090
  servlet:
    context-path: /demo

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - metrics
  endpoint:
    health:
      show-details: always

spring:
  datasource:
    url: jdbc:mysql://docker:3306/demo
    username: dbuser
    password: Aa123456!
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: create

#  jackson:
#    serialization:
#      wrap-root-value: true
#    deserialization:
#      unwrap-root-value: true
#      fail-on-unknown-properties: false
