server:
  servlet:
    context-path: /demo

spring:
  datasource:
    url: jdbc:mysql://docker:3306/demo
    username: dbuser
    password: Aa123456!
    initialization-mode: always

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          batch_size: 10
          time_zone: UTC
        order_inserts: true
        order_updates: true
        session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 25

#  jackson:
#    serialization:
#      wrap-root-value: true
#    deserialization:
#      unwrap-root-value: true
#      fail-on-unknown-properties: false
