server:
  port: 8090
  servlet:
    context-path: /demo

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - metrics
  endpoint:
    health:
      show-details: always


info:
  app:
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@

spring:
  datasource:
    url: jdbc:mysql://docker:3306/demo
    username: dbuser
    password: Aa123456!
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: create