app:
  users:
  - { id: 1, first-name: Michael, last-name: Jordan, age: 50 }
  - { id: 2, first-name: Erwin, last-name: Johnson, age: 55 }
  - { id: 3, first-name: Larry, last-name: Bird, age: 53 }

server:
  port: 8090
  servlet:
    context-path: /demo

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - metrics
  endpoint:
    health:
      show-details: always

  metrics:
    export:
      graphite:
        host: 127.0.0.1
        step: 5s
        # Run graphite and update ip/port before enabling
        enabled: true
    web:
      server:
        request:
          autotime:
            enabled: true

info:
  app:
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
