users:
  - { id: 1, first-name: Michael, last-name: Jordan, age: 50 }
  - { id: 2, first-name: Erwin, last-name: Johnson, age: 55 }
  - { id: 3, first-name: Larry, last-name: Bird, age: 53 }
  
server:
  port: 8090
  servlet:
    context-path: /boot

info:
  app:
     encoding: @project.build.sourceEncoding@
     java:
       source: @java.version@
