server:
  port: 8090
  servlet:
    context-path: /demo

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - metrics
  endpoint:
    health:
      show-details: always

spring:
  datasource:
    url: jdbc:mysql://docker:3306/demo
    username: dbuser
    password: Aa123456!
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true
    open-in-view: false

  sql:
    init:
      enabled: true

#  jackson:
#    serialization:
#      wrap-root-value: true
#    deserialization:
#      unwrap-root-value: true
#      fail-on-unknown-properties: false
