app:
  users:
  - { id: 1, first-name: Michael, last-name: Jordan, age: 50 }
  - { id: 2, first-name: Erwin, last-name: Johnson, age: 55 }
  - { id: 3, first-name: Larry, last-name: Bird, age: 53 }
  http-service:
    url: https://some-domain.com:8080
#    connect-timeout: 5s
#    read-timeout: 10s
#    max-retries: 3

server:
  port: 8090
  servlet:
    context-path: /demo
  error:
    whitelabel:
      enabled: false
  shutdown: graceful
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  config:
    import:
    - "${app.config.dir:classpath:}external.yml"
  lifecycle:
    timeout-per-shutdown-phase: 30s
  output:
    ansi:
      enabled: always

management:
  server:
    port: 8091
  endpoints:
    web:
      exposure:
        include:
        - info
        - env
        - health
        - metrics
    #      cors:
    #        allowed-origins: "*"
  endpoint:
    health:
      show-details: always
      probes:
        # This is useful for exposing the liveness group on the server port, since we exposed the actuator endpoints
        #  on the management port (via management.server.port). It's as if we set:
        #  management.endpoint.health.group.liveness.additional-path="server:livez"
        #  For the readiness group, see below.
        add-additional-paths: true
        # probes.enabled is only needed if you'd like to check this locally. On k8s, it is enabled by default
        enabled: true
      group:
        readiness:
          # This would typically include external resources critical to the app like db
          include: readinessState, db
          # This is no longer needed since 2.7.3 (default additional path wasn't created when group was explicitly defined
          # additional-path: server:/readyz
  metrics:
    export:
      graphite:
        step: 5s
        # Run graphite and update ip/port before enabling (default is localhost:2004)
        enabled: false
        graphite-tags-enabled: false
    web:
      server:
        request:
          autotime:
            enabled: true



info:
  app:
    #    encoding: @project.build.sourceEncoding@
    encoding: UTF-8
    java:
      #      source: @java.version@
      source: 1.0.0
