app:
  users:
    - { id: 1, first-name: Michael, last-name: Jordan, age: 50 }
    - { id: 2, first-name: Erwin, last-name: Johnson, age: 55 }
    - { id: 3, first-name: Larry, last-name: Bird, age: 53 }

server:
  port: 8090
  servlet:
    context-path: /demo
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - metrics
#      cors:
#        allowed-origins: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          # This would typically include external resources critical to the app like db
          include: readinessState,info


  metrics:
    export:
      graphite:
        host: 127.0.0.1
        step: 5s
        # Run graphite and update ip/port before enabling
        enabled: false
    web:
      server:
        request:
          autotime:
            enabled: true

info:
  app:
    #    encoding: @project.build.sourceEncoding@
    encoding: UTF-8
    java:
      #      source: @java.version@
      source: 1.0.0
