version: "3.8"
services:
  graphite:
    image: graphiteapp/graphite-statsd:latest
    ports:
    - "80:80"
    - "2003-2004:2003-2004"
    - "2023-2024:2023-2024"
    - "8125:8125/udp"
    - "8126:8126"
  grafana:
    image: grafana/grafana:latest
    ports:
    - "3000:3000"
    volumes:
    - ./grafana-provisioning:/etc/grafana/provisioning
    environment:
    - GF_SECURITY_ADMIN_USER=demo
    - GF_SECURITY_ADMIN_PASSWORD=demo
